# k8s/regional-node/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenzro-regional-node
  namespace: tenzro-network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenzro-regional-node
  template:
    metadata:
      labels:
        app: tenzro-regional-node
    spec:
      containers:
        - name: regional-node
          image: tenzro/regional-node:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_TYPE
              value: "regional_node"
            - name: NODE_TIER
              value: "aggregator"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10